# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/full_testbench_bd/full_testbench_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd || ORIG_REF_NAME==full_testbench_bd} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_xlslice_0_0/full_testbench_bd_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_xlslice_0_0 || ORIG_REF_NAME==full_testbench_bd_xlslice_0_0} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_xlslice_1_0/full_testbench_bd_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_xlslice_1_0 || ORIG_REF_NAME==full_testbench_bd_xlslice_1_0} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_xlslice_0_1/full_testbench_bd_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_xlslice_0_1 || ORIG_REF_NAME==full_testbench_bd_xlslice_0_1} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_xlslice_1_1/full_testbench_bd_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_xlslice_1_1 || ORIG_REF_NAME==full_testbench_bd_xlslice_1_1} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_alu_0_0/full_testbench_bd_alu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_alu_0_0 || ORIG_REF_NAME==full_testbench_bd_alu_0_0} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_alu_op_A_0/full_testbench_bd_alu_op_A_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_alu_op_A_0 || ORIG_REF_NAME==full_testbench_bd_alu_op_A_0} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_alu_op_B_0/full_testbench_bd_alu_op_B_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_alu_op_B_0 || ORIG_REF_NAME==full_testbench_bd_alu_op_B_0} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_cu_ram_0_0/full_testbench_bd_cu_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_cu_ram_0_0 || ORIG_REF_NAME==full_testbench_bd_cu_ram_0_0} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_general_registers_0_0/full_testbench_bd_general_registers_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_general_registers_0_0 || ORIG_REF_NAME==full_testbench_bd_general_registers_0_0} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_multiplexer_0_0/full_testbench_bd_multiplexer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_multiplexer_0_0 || ORIG_REF_NAME==full_testbench_bd_multiplexer_0_0} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_multiplexer_0_1/full_testbench_bd_multiplexer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_multiplexer_0_1 || ORIG_REF_NAME==full_testbench_bd_multiplexer_0_1} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_control_unit_0_0/full_testbench_bd_control_unit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_control_unit_0_0 || ORIG_REF_NAME==full_testbench_bd_control_unit_0_0} -quiet] -quiet

# IP: bd/full_testbench_bd/ip/full_testbench_bd_program_memory_0_0/full_testbench_bd_program_memory_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==full_testbench_bd_program_memory_0_0 || ORIG_REF_NAME==full_testbench_bd_program_memory_0_0} -quiet] -quiet

# XDC: c:/Users/LOLNO/CPU_Project/CPU_Project.gen/sources_1/bd/full_testbench_bd/full_testbench_bd_ooc.xdc
